In [11]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

In [22]:
M = [[8, -19, -25, 6], [-32, 44, 20, -23], [16, 17, 20, -40]]
M = np.array(M)

array([[ 2.40100492e+00, -5.29218983e+00, -1.23722422e+01,
         6.28168280e+02],
       [ 3.59147769e-01, -9.76761469e-01, -6.60023590e+00,
         3.26017669e+02],
       [ 7.58847639e-04, -8.09779334e-03, -1.90063594e-02,
         1.00000000e+00]])

In [39]:
q1 = np.array(M[0])
q2 = np.array(M[1])
q3 = np.array(M[2])

In [42]:
ox = q1.transpose().dot(q3)
oy = q2.transpose().dot(q3)
print(ox,oy)

-935 1556


In [43]:
fx = np.sqrt(abs(q1.transpose().dot(q1) - ox**2))
fy = np.sqrt(abs(q2.transpose().dot(q2) - oy**2))
print(fx,fy)

934.419070867028 1554.7498191027391


In [45]:
r11 = (ox*M[2][0] - M[0][0])/fx
r12 = (ox*M[2][1] - M[0][1])/fx
r13 = (ox*M[2][2] - M[0][2])/fx
print(r11, r12, r13)

-16.018508682738574 -16.99023542538466 -19.98567942611858


In [46]:
r21 = (oy*M[2][0] - M[1][0])/fy
r22 = (oy*M[2][1] - M[1][1])/fy
r23 = (oy*M[2][2] - M[1][2])/fy
print(r21, r22, r23)

16.033447757135733 16.985369398685833 20.003218278518986


In [44]:
Tx = (ox*M[2][3] - M[0][3])/fx
Ty = (oy*M[2][3] - M[1][3])/fy
print(Tx, Ty)

40.01844693227728 -40.01737079210983


In [6]:
import numpy as np
M = [[8, -19, -25, 6], [-32, 44, 20, -23], [16, 17, 20, -40]]
M = np.array(M)

Z = np.array([4,2,3,1])
print(M, Z)
print(M.dot(Z))

[[  8 -19 -25   6]
 [-32  44  20 -23]
 [ 16  17  20 -40]] [4 2 3 1]
[-75  -3 118]


In [8]:
3/118

0.025423728813559324

In [13]:
from math import sqrt
Tx = [[1,0,0,-25],[0,1,0,-10],[0,0,1,-12],[0,0,0,1]]
Tx = np.array(Tx)

Rx =  [[1,0,0,0],[0,sqrt(3)/2,1/2,0],[0,-1/2,sqrt(3)/2,0],[0,0,0,1]]
Rx = np.array(Rx)

Ry = [[1/sqrt(2),0,-1/sqrt(2),0],[0,1,0,0],[1/sqrt(2),0,1/sqrt(2),0],[0,0,0,1]]
Ry = np.array(Ry)

A = np.array([4,3,2,1])

In [14]:
Tx.dot(Rx).dot(Ry).dot(A)

array([-23.58578644,  -5.28060345,  -9.82576539,   1.        ])

In [38]:
M = [[8, -19, -25, 6], [-32, 44, 20, -23], [16, 17, 20, -40]]
M = np.array(M)

In [30]:
A = np.array([3,3,3,1])


In [31]:
M.dot(A)

array([-102,   73,  119])

In [32]:
0.85-0.63

0.21999999999999997

In [33]:
0.22*0.22

0.0484

In [34]:
0.61*0.61

0.3721

In [35]:
0.3721+0.0484

0.4205

In [36]:
sqrt(0.4205)

0.648459713474939

In [37]:
1.414/0.64

2.2093749999999996

In [48]:
R = [[-16, -17, -20], [16, 17, 20], [16, 17, 20]]
R = np.array(R)

X = [[1,0,0],[0,sqrt(3)/2,1/2],[0,1/2,sqrt(3)/2]]
X = np.array(X)

Y = [[1/sqrt(2),0,-1/sqrt(2)],[0,1,0],[1/sqrt(2),0,1/sqrt(2)]]
Y = np.array(Y)

In [49]:
R.dot(X).dot(Y)

array([[-29.57156485, -24.72243186,  -6.94414786],
       [ 29.57156485,  24.72243186,   6.94414786],
       [ 29.57156485,  24.72243186,   6.94414786]])